module: elearning

entities:
  - name: Course
    fields:
      - name: title
        type: String
        validation:
          notNull: true
          size:
            min: 3
            max: 100
      - name: description
        type: String
        validation:
          size:
            max: 500
      - name: createdAt
        type: LocalDateTime
      - name: updatedAt
        type: LocalDateTime
    relationships:
      - name: lessons
        type: Lesson
        relationType: OneToMany
        mappedBy: course
        inverseField: course
        fetch: LAZY
      - name: instructor
        type: Instructor
        relationType: ManyToOne
        joinColumn: instructor_id
        inverseField: courses
        fetch: EAGER

  - name: Instructor
    fields:
      - name: firstName
        type: String
        validation:
          notNull: true
          size:
            min: 2
            max: 50
      - name: lastName
        type: String
        validation:
          notNull: true
          size:
            min: 2
            max: 50
      - name: email
        type: String
        validation:
          notNull: true
          email: true
      - name: createdAt
        type: LocalDateTime
      - name: updatedAt
        type: LocalDateTime
    relationships:
      - name: courses
        type: Course
        relationType: OneToMany
        mappedBy: instructor
        inverseField: instructor
        fetch: LAZY

  - name: Lesson
    fields:
      - name: title
        type: String
        validation:
          notNull: true
          size:
            min: 3
            max: 100
      - name: content
        type: String
        validation:
          notNull: true
      - name: createdAt
        type: LocalDateTime
      - name: updatedAt
        type: LocalDateTime
    relationships:
      - name: course
        type: Course
        relationType: ManyToOne
        joinColumn: course_id
        inverseField: lessons
        fetch: EAGER
